import Head from "next/head";
import { StyledHeader, StyledNav } from "./Header.style";
import Button from "@components/Button/Button";

const Header = (props: any) => {
  return (
    <>
      <Head>
        <title>My Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <StyledHeader>
        <StyledNav>
          <h1>로고</h1>
          <Button>로그인</Button>
        </StyledNav>
      </StyledHeader>
    </>
  );
};

const DefaultHeading = () => {
  return (
    <StyledHeader>
      <StyledNav>
        <h1>로고</h1>
        <Button>로그인</Button>
      </StyledNav>
    </StyledHeader>
  );
}

const ExceptionalHeading = () => {
  return (
    <StyledHeader>
      <StyledNav>
        <h1>로고</h1>
        뒤로가기
      </StyledNav>
    </StyledHeader>
  );
}

export default Header;