import Head from "next/head";
import { StyledHeader, StyledNav } from "./Header.style";
import Button from "@components/Button/Button";
import Icon from "@components/Icon/Icon";
import { AiOutlineLeft } from "react-icons/ai";

const Header = (props: any) => {
  return (
    <>
      <Head>
        <title>My Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      { props.default ? <DefaultHeading /> : <ExceptionalHeading /> }
    </>
  );
};
// FIXME : 로그인 정보가 있을때 없을때 구분하여 버튼컴포넌트 하나만 보이도록 설정한다. (차후 db연동 시)
const DefaultHeading = () => {
  return (
    <StyledHeader>
      <StyledNav>
        <span>로고</span>
        <Button active>로그인</Button>
        {/* <Button>로그아웃</Button> */}
      </StyledNav>
    </StyledHeader>
  );
}

const ExceptionalHeading = () => {
  return (
    <StyledHeader>
      <StyledNav icon>
        <Icon size={32}>
          <AiOutlineLeft />
        </Icon>
      </StyledNav>
    </StyledHeader>
  );
}


export default Header;